apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edu-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: edu.local
    http:
      paths:
      - path: /home
        pathType: Prefix
        backend:
          service:
            name: edu-app-svc
            port:
              number: 80
      - path: /courses
        pathType: Prefix
        backend:
          service:
            name: edu-app-svc
            port:
              number: 80
      - path: /blog
        pathType: Prefix
        backend:
          service:
            name: edu-app-svc
            port:
              number: 80
